import './style.css';
import * as THREE from 'three';

declare global { interface Window { __AETHERPLAY__: GameSnapshot } }
type Phase = 'ready' | 'playing' | 'paused' | 'won' | 'lost';
type GameSnapshot = { phase: Phase; score: number; player: {x:number;y:number;z:number}; relaysRestored:number; charge:number; seed:94721; restartCount:number; objective:string; speed:number };

const root=document.querySelector<HTMLDivElement>('#app'); if(!root)throw new Error('Missing #app root');
root.innerHTML=`
<div id="game" aria-label="Signal Drift 3D game"></div><div class="grain"></div><div class="vignette"></div>
<header class="brand"><span class="brand-mark"></span><span>SIGNAL DRIFT</span><small>COURIER // 07</small></header>
<div id="hud" class="hud hidden"><section class="charge-card"><div class="label-row"><span>CORE CHARGE</span><strong id="charge-number">100</strong></div><div class="meter"><i id="charge-fill"></i></div></section><section class="relay-card"><span class="eyebrow">RELAY SEQUENCE</span><div class="relay-dots"><i></i><i></i><i></i></div><strong id="relay-count">0 / 3</strong></section><section class="objective-card"><span class="eyebrow">CURRENT VECTOR</span><strong id="objective">REACH RELAY 01</strong><span id="distance">—</span></section></div>
<div id="warning" class="warning">IMPACT</div><div id="toast" class="toast"><span>RELAY 01</span><strong>UPLINK RESTORED</strong></div>
<div id="intro" class="overlay intro"><div class="kicker"><i></i> STORM COURIER PROTOCOL</div><h1>SIGNAL<br><em>DRIFT</em></h1><p class="lede">Fly the broken skyway. Restore three relay gates in order, gather charge, then cross extraction.</p><div class="mission-grid"><div><span>01</span><p><b>RESTORE</b>Fly through each cyan relay</p></div><div><span>02</span><p><b>SURVIVE</b>Dodge red storm machinery</p></div><div><span>03</span><p><b>EXTRACT</b>Keep your core charged</p></div></div><button id="start"><span>LAUNCH COURIER</span><kbd>ENTER</kbd></button><div class="controls"><span><b>WASD / ARROWS</b> STEER</span><span><b>SHIFT / SPACE</b> BOOST</span><span class="touch-copy"><b>DRAG</b> STEER · <b>HOLD BOOST</b></span></div></div>
<div id="result" class="overlay result hidden"><div class="kicker"><i></i> <span id="result-kicker">MISSION STATUS</span></div><h2 id="result-title">SIGNAL<br><em>SECURED</em></h2><p id="result-copy">The relay field is back online.</p><div class="result-stats"><div><span>RELAYS</span><b id="result-relays">3 / 3</b></div><div><span>SCORE</span><b id="result-score">0000</b></div><div><span>CHARGE</span><b id="result-charge">00%</b></div></div><button id="restart"><span>FLY AGAIN</span><kbd>R</kbd></button></div>
<div id="pause" class="pause hidden"><span>LINK SUSPENDED</span><small>Return to continue</small></div><div id="touch" class="touch-ui hidden"><div id="stick"><i></i><span>STEER</span></div><button id="boost">BOOST</button></div><footer><span>ALT // CLOUD DECK</span><span id="speed">000 KM/H</span></footer>`;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!; const gameEl=$('#game'),hud=$('#hud'),intro=$('#intro'),result=$('#result'),pauseEl=$('#pause'),chargeFill=$('#charge-fill'),chargeNumber=$('#charge-number'),objectiveEl=$('#objective'),distanceEl=$('#distance'),relayCount=$('#relay-count'),warning=$('#warning'),toast=$('#toast'),speedEl=$('#speed'),touchUi=$('#touch'),stick=$('#stick'),boostBtn=$('#boost');

const scene=new THREE.Scene();scene.background=new THREE.Color(0x061018);scene.fog=new THREE.FogExp2(0x07131b,.0085);
const camera=new THREE.PerspectiveCamera(67,innerWidth/innerHeight,.1,600);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.22;renderer.shadowMap.enabled=true;gameEl.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0x72dffc,0x081017,1.45));const sun=new THREE.DirectionalLight(0xbfeaff,3.2);sun.position.set(-35,55,25);scene.add(sun);const world=new THREE.Group();scene.add(world);
const matDark=new THREE.MeshStandardMaterial({color:0x13232b,metalness:.82,roughness:.32}),matEdge=new THREE.MeshStandardMaterial({color:0x1c5964,emissive:0x00bcd4,emissiveIntensity:1.4,metalness:.5,roughness:.25}),matCyan=new THREE.MeshStandardMaterial({color:0xbffcff,emissive:0x00dcff,emissiveIntensity:4,metalness:.25,roughness:.18}),matRed=new THREE.MeshStandardMaterial({color:0xff315a,emissive:0xe40038,emissiveIntensity:4,metalness:.4,roughness:.24}),matAmber=new THREE.MeshStandardMaterial({color:0xffd86a,emissive:0xff9d00,emissiveIntensity:4,metalness:.25,roughness:.16});
function mesh(g:THREE.BufferGeometry,m:THREE.Material,p:THREE.Object3D=world){const o=new THREE.Mesh(g,m);p.add(o);return o}
let randomSeed=94721;const rand=()=>((randomSeed=(randomSeed*1664525+1013904223)>>>0)/4294967296);
const cloudGeo=new THREE.IcosahedronGeometry(6,1),cloudMat=new THREE.MeshStandardMaterial({color:0x637985,roughness:1,flatShading:true,transparent:true,opacity:.58}),clouds=new THREE.InstancedMesh(cloudGeo,cloudMat,150),dummy=new THREE.Object3D();for(let i=0;i<150;i++){dummy.position.set((rand()-.5)*180,-11-rand()*7,35-rand()*360);dummy.scale.set(1+rand()*2.4,.35+rand()*.5,1+rand()*2.5);dummy.rotation.set(rand(),rand(),rand());dummy.updateMatrix();clouds.setMatrixAt(i,dummy.matrix)}world.add(clouds);
for(const x of [-12,12]){const rail=mesh(new THREE.BoxGeometry(.22,.22,310),matEdge);rail.position.set(x,-1,-122);for(let z=25;z>-285;z-=18){const p=mesh(new THREE.BoxGeometry(.8,10,.8),matDark);p.position.set(x,-5,z);const lamp=mesh(new THREE.BoxGeometry(1.1,.18,1.1),matCyan);lamp.position.set(x,.1,z)}}for(let z=24;z>-280;z-=12){const dash=mesh(new THREE.BoxGeometry(.12,.05,4),matEdge);dash.position.set(0,-.85,z)}for(let i=0;i<24;i++){const side=i%2?-1:1,z=10-i*13,tower=mesh(new THREE.CylinderGeometry(.8,1.8,18+rand()*18,5),matDark);tower.position.set(side*(24+rand()*32),2,z);tower.rotation.z=side*(.05+rand()*.08);const cap=mesh(new THREE.OctahedronGeometry(1.3),i%3===0?matRed:matEdge);cap.position.copy(tower.position).add(new THREE.Vector3(0,11,0))}
type Gate={group:THREE.Group;center:THREE.Vector3;restored:boolean;ring:THREE.Mesh;core:THREE.Mesh};const gates:Gate[]=[];[[0,7,-48],[4,9,-116],[-3,6,-186]].forEach((d,idx)=>{const group=new THREE.Group();group.position.set(d[0],d[1],d[2]);world.add(group);const ring=mesh(new THREE.TorusGeometry(8,.55,10,48),matCyan,group);ring.rotation.z=idx*.22;const outer=mesh(new THREE.TorusGeometry(10.2,.12,8,48),matEdge,group);outer.rotation.z=-idx*.28;for(let k=0;k<8;k++){const a=k/8*Math.PI*2,tab=mesh(new THREE.BoxGeometry(.55,1.8,.5),matDark,group);tab.position.set(Math.cos(a)*9.1,Math.sin(a)*9.1,0);tab.rotation.z=a}const core=mesh(new THREE.OctahedronGeometry(1.05),matCyan,group);core.position.y=-10.5;gates.push({group,center:new THREE.Vector3(...d),restored:false,ring,core})});
const extraction=new THREE.Group();extraction.position.set(0,8,-258);world.add(extraction);for(let i=0;i<3;i++){const r=mesh(new THREE.TorusGeometry(10+i*1.55,.24,8,64),i===1?matAmber:matCyan,extraction);r.position.z=i*.8}const beam=mesh(new THREE.CylinderGeometry(6,6,34,24,1,true),new THREE.MeshBasicMaterial({color:0x00ddff,transparent:true,opacity:.05,side:THREE.DoubleSide}),extraction);beam.rotation.x=Math.PI/2;
type Hazard={group:THREE.Group;z:number;speed:number;cooldown:number};const hazards:Hazard[]=[];[[-4,6,-78,1.15],[5,8,-145,-1.35],[0,6,-217,1.55]].forEach(d=>{const g=new THREE.Group();g.position.set(d[0],d[1],d[2]);world.add(g);mesh(new THREE.IcosahedronGeometry(1.25,1),matRed,g);for(let k=0;k<3;k++){const arm=mesh(new THREE.BoxGeometry(13,.65,.7),matDark,g);arm.rotation.z=k*Math.PI/3;const tip=mesh(new THREE.BoxGeometry(2.2,1.1,1.1),matRed,g);tip.position.set(Math.cos(k*Math.PI/3)*6,Math.sin(k*Math.PI/3)*6,0);tip.rotation.z=k*Math.PI/3}hazards.push({group:g,z:d[2],speed:d[3],cooldown:0})});
type Pickup={mesh:THREE.Mesh;taken:boolean;baseY:number};const pickups:Pickup[]=[];[[-7,5,-29],[7,8,-66],[-6,11,-96],[8,5,-132],[-8,8,-164],[6,10,-204],[-5,5,-232]].forEach(d=>{const p=mesh(new THREE.OctahedronGeometry(1.1),matAmber);p.position.set(d[0],d[1],d[2]);const halo=mesh(new THREE.TorusGeometry(1.7,.09,6,24),matAmber,p);halo.rotation.x=Math.PI/2;pickups.push({mesh:p,taken:false,baseY:d[1]})});
const craft=new THREE.Group();scene.add(craft);const body=mesh(new THREE.ConeGeometry(1.05,4.4,6),matDark,craft);body.rotation.x=-Math.PI/2;const canopy=mesh(new THREE.SphereGeometry(.72,12,8,0,Math.PI*2,0,Math.PI*.55),new THREE.MeshStandardMaterial({color:0x7fffff,emissive:0x007b8f,emissiveIntensity:2,metalness:.8,roughness:.1}),craft);canopy.position.set(0,.55,-.4);canopy.scale.z=1.5;const wing=mesh(new THREE.BoxGeometry(4.1,.18,1.25),matDark,craft);wing.position.z=.55;for(const x of [-1.45,1.45]){const engine=mesh(new THREE.CylinderGeometry(.32,.42,1.5,10),matEdge,craft);engine.position.set(x,-.12,.65);engine.rotation.x=Math.PI/2;const flame=mesh(new THREE.ConeGeometry(.27,2,10),matCyan,craft);flame.position.set(x,-.12,1.85);flame.rotation.x=-Math.PI/2}const trailMat=new THREE.MeshBasicMaterial({color:0x00eaff,transparent:true,opacity:.32,blending:THREE.AdditiveBlending,depthWrite:false});for(const x of [-1.45,1.45]){const trail=mesh(new THREE.CylinderGeometry(.05,.4,9,8,1,true),trailMat,craft);trail.position.set(x,-.12,5.3);trail.rotation.x=Math.PI/2}const shield=mesh(new THREE.SphereGeometry(2.7,16,10),new THREE.MeshBasicMaterial({color:0x54eeff,wireframe:true,transparent:true,opacity:0}),craft);

const keys=new Set<string>();let pointer={x:0,y:0,active:false};let phase:Phase='ready',previousPhase:Phase='ready',restartCount=0,relayIndex=0,charge=100,score=0,speed=24,impact=0,elapsed=0;const player=new THREE.Vector3(0,7,15),velocity=new THREE.Vector2();const snapshot:GameSnapshot={phase,score,player:{x:0,y:7,z:15},relaysRestored:0,charge:100,seed:94721,restartCount:0,objective:'Reach relay 01',speed};window.__AETHERPLAY__=snapshot;
function setPhase(v:Phase){phase=v;snapshot.phase=v}function objective(){return relayIndex<3?`REACH RELAY 0${relayIndex+1}`:'CROSS EXTRACTION'}function targetZ(){return relayIndex<3?gates[relayIndex].center.z:extraction.position.z}
function resetGame(){restartCount++;relayIndex=0;charge=100;score=0;speed=24;impact=0;elapsed=0;player.set(0,7,15);velocity.set(0,0);gates.forEach(g=>{g.restored=false;g.ring.material=matCyan;g.group.visible=true});pickups.forEach(p=>{p.taken=false;p.mesh.visible=true});result.classList.add('hidden');intro.classList.add('hidden');hud.classList.remove('hidden');touchUi.classList.toggle('hidden',!(matchMedia('(pointer: coarse)').matches||innerWidth<=600));setPhase('playing');updateUI()}
function endGame(won:boolean){setPhase(won?'won':'lost');hud.classList.add('hidden');touchUi.classList.add('hidden');result.classList.remove('hidden');$('#result-kicker').textContent=won?'ROUTE COMPLETE':'COURIER LOST';$('#result-title').innerHTML=won?'SIGNAL<br><em>SECURED</em>':'CORE<br><em>OFFLINE</em>';$('#result-copy').textContent=won?'The relay field is back online. The storm has a path through it.':'The cloud deck claimed the signal. Reconnect and fly again.';$('#result-relays').textContent=`${relayIndex} / 3`;$('#result-score').textContent=Math.floor(score).toString().padStart(4,'0');$('#result-charge').textContent=`${Math.max(0,Math.round(charge))}%`;$('#restart').querySelector('span')!.textContent=won?'FLY AGAIN':'RETRY ROUTE'}
function flash(text:string,danger=false){warning.textContent=text;warning.classList.toggle('danger',danger);warning.classList.remove('show');void warning.offsetWidth;warning.classList.add('show')}function relayRestored(){const g=gates[relayIndex];g.restored=true;g.ring.material=matAmber;relayIndex++;score+=1000;charge=Math.min(100,charge+18);toast.querySelector('span')!.textContent=`RELAY 0${relayIndex}`;toast.classList.remove('show');void toast.offsetWidth;toast.classList.add('show')}
function updateUI(){chargeFill.style.width=`${Math.max(0,charge)}%`;chargeFill.classList.toggle('low',charge<26);chargeNumber.textContent=Math.ceil(Math.max(0,charge)).toString();objectiveEl.textContent=objective();distanceEl.textContent=`${Math.max(0,Math.round((player.z-targetZ())*3.2))} M`;relayCount.textContent=`${relayIndex} / 3`;document.querySelectorAll('.relay-dots i').forEach((d,i)=>d.classList.toggle('on',i<relayIndex));speedEl.textContent=`${Math.round(speed*10).toString().padStart(3,'0')} KM/H`;Object.assign(snapshot,{phase,score:Math.floor(score),player:{x:+player.x.toFixed(2),y:+player.y.toFixed(2),z:+player.z.toFixed(2)},relaysRestored:relayIndex,charge:+Math.max(0,charge).toFixed(2),restartCount,objective:objective(),speed:+speed.toFixed(1)})}
function update(dt:number,t:number){elapsed+=dt;const ix=((keys.has('ArrowRight')||keys.has('KeyD'))?1:0)-((keys.has('ArrowLeft')||keys.has('KeyA'))?1:0)+(pointer.active?pointer.x:0),iy=((keys.has('ArrowUp')||keys.has('KeyW'))?1:0)-((keys.has('ArrowDown')||keys.has('KeyS'))?1:0)+(pointer.active?-pointer.y:0),boosting=keys.has('ShiftLeft')||keys.has('ShiftRight')||keys.has('Space')||boostBtn.classList.contains('held'),canBoost=boosting&&charge>8;speed=THREE.MathUtils.damp(speed,canBoost?37:24,2.8,dt);charge-=dt*(canBoost?4.3:1.18);score+=dt*speed*.5;velocity.x=THREE.MathUtils.damp(velocity.x,ix*12,5.5,dt);velocity.y=THREE.MathUtils.damp(velocity.y,iy*10,5.5,dt);player.x+=velocity.x*dt;player.y+=velocity.y*dt;player.z-=speed*dt;player.x=THREE.MathUtils.clamp(player.x,-15,15);player.y=THREE.MathUtils.clamp(player.y,1,16);craft.position.copy(player);craft.rotation.z=THREE.MathUtils.damp(craft.rotation.z,-velocity.x*.045,7,dt);craft.rotation.x=THREE.MathUtils.damp(craft.rotation.x,velocity.y*.022,7,dt);craft.position.y+=Math.sin(t*5)*.08;
 const gate=gates[relayIndex];if(gate&&Math.abs(player.z-gate.center.z)<1.8){const dist=Math.hypot(player.x-gate.center.x,player.y-gate.center.y);if(dist<7.1)relayRestored();else if(dist<10.8){charge-=16;impact=1;flash('GATE IMPACT',true)}}hazards.forEach(h=>{h.group.rotation.z+=h.speed*dt;h.cooldown-=dt;if(Math.abs(player.z-h.z)<2.2&&h.cooldown<=0){const local=new THREE.Vector2(player.x-h.group.position.x,player.y-h.group.position.y),a=-h.group.rotation.z,ry=local.x*Math.sin(a)+local.y*Math.cos(a);if(Math.abs(ry)<1.3&&local.length()<7.4){charge-=24;score=Math.max(0,score-150);impact=1;h.cooldown=2;flash('STORM IMPACT',true)}}});pickups.forEach((p,i)=>{if(p.taken)return;p.mesh.rotation.y+=dt*2.5;p.mesh.rotation.z+=dt;p.mesh.position.y=p.baseY+Math.sin(t*2+i)*.4;if(player.distanceTo(p.mesh.position)<3){p.taken=true;p.mesh.visible=false;charge=Math.min(100,charge+28);score+=250;flash('+ CORE CHARGE')}});if(relayIndex===3&&Math.abs(player.z-extraction.position.z)<2.2&&Math.hypot(player.x,player.y-extraction.position.y)<9.5){score+=Math.round(charge*20);endGame(true)}if(charge<=0||player.z<-280)endGame(false);impact=THREE.MathUtils.damp(impact,0,4,dt);(shield.material as THREE.Material).opacity=impact*.42;shield.scale.setScalar(1+impact*.18);gates.forEach((g,i)=>{g.ring.rotation.z+=(g.restored?.7:1.4)*dt*(i%2?1:-1);g.core.rotation.y+=dt*2});extraction.rotation.z+=dt*.22;clouds.position.z=(elapsed*1.5)%18;const camTarget=new THREE.Vector3(player.x*.48,player.y+4.2,player.z+12.8);camera.position.lerp(camTarget,1-Math.exp(-5*dt));camera.position.x+=(Math.random()-.5)*impact*.55;camera.position.y+=(Math.random()-.5)*impact*.4;camera.lookAt(player.x*.2,player.y+.4,player.z-13);camera.fov=THREE.MathUtils.damp(camera.fov,canBoost?76:67,4,dt);camera.updateProjectionMatrix();updateUI()}
const clock=new THREE.Clock();function animate(ms:number){requestAnimationFrame(animate);const t=ms/1000,dt=Math.min(.033,clock.getDelta());if(phase==='playing')update(dt,t);else{gates.forEach((g,i)=>g.group.rotation.z=Math.sin(t*.25+i)*.08);craft.position.y+=Math.sin(t*1.7)*.002}renderer.render(scene,camera)}craft.position.copy(player);camera.position.set(0,12,29);camera.lookAt(0,7,-20);animate(0);updateUI();
$('#start').addEventListener('click',resetGame);$('#restart').addEventListener('click',resetGame);addEventListener('keydown',e=>{keys.add(e.code);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if((phase==='ready'&&e.code==='Enter')||((phase==='won'||phase==='lost')&&(e.code==='KeyR'||e.code==='Enter')))resetGame()});addEventListener('keyup',e=>keys.delete(e.code));function pointerMove(e:PointerEvent){if(!pointer.active)return;const r=stick.getBoundingClientRect();pointer.x=THREE.MathUtils.clamp((e.clientX-(r.left+r.width/2))/(r.width*.42),-1,1);pointer.y=THREE.MathUtils.clamp((e.clientY-(r.top+r.height/2))/(r.height*.42),-1,1);(stick.querySelector('i') as HTMLElement).style.transform=`translate(${pointer.x*32}px,${pointer.y*32}px)`}stick.addEventListener('pointerdown',e=>{pointer.active=true;stick.setPointerCapture(e.pointerId);pointerMove(e)});stick.addEventListener('pointermove',pointerMove);stick.addEventListener('pointerup',()=>{pointer={x:0,y:0,active:false};(stick.querySelector('i') as HTMLElement).style.transform=''});for(const ev of ['pointerdown','pointerup','pointercancel','pointerleave'])boostBtn.addEventListener(ev,e=>{e.preventDefault();boostBtn.classList.toggle('held',ev==='pointerdown')});document.addEventListener('visibilitychange',()=>{if(document.hidden&&phase==='playing'){previousPhase=phase;setPhase('paused');pauseEl.classList.remove('hidden')}else if(!document.hidden&&phase==='paused'&&previousPhase==='playing'){setPhase('playing');pauseEl.classList.add('hidden');clock.getDelta()}});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight)});
