import * as THREE from 'three';
import './style.css';

const app = document.querySelector<HTMLDivElement>('#app');
if (!app) throw new Error('Missing #app root');

type Phase = 'ready' | 'playing' | 'paused' | 'won' | 'lost';
type Pickup = { mesh: THREE.Group; position: THREE.Vector3; collected: boolean; spin: number };
type Hazard = { mesh: THREE.Group; base: THREE.Vector3; radius: number; phase: number; sway: number; hit: boolean };
type Relay = { mesh: THREE.Group; position: THREE.Vector3; restored: boolean; number: number };
const SEED = 94721;
let seed = SEED;
const random = () => { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; };
const clamp = THREE.MathUtils.clamp;

app.innerHTML = `
  <main class="game-shell">
    <div class="vignette"></div><div class="scanlines"></div>
    <section class="hud" aria-live="polite">
      <div class="brand"><span class="brand-mark">◈</span> SIGNAL DRIFT</div>
      <div class="hud-right"><div class="relay-readout"><span class="tiny-label">RELAY LINK</span><span id="relayText">0 / 3</span></div><div class="charge-box"><span class="tiny-label">CHARGE</span><div class="charge-track"><i id="chargeFill"></i></div><span id="chargeText">100%</span></div></div>
    </section>
    <div class="objective" id="objective"><span class="objective-pip"></span><span id="objectiveText">SYSTEM STANDBY</span></div>
    <section class="hero-panel" id="startPanel">
      <div class="eyebrow">STORM // 07.31 // COURIER CHANNEL</div><h1>SIGNAL<br><em>DRIFT</em></h1>
      <p>Thread the broken relay field. Restore the three gates in sequence, harvest charge, and ride the extraction signal home.</p>
      <button class="launch-button" id="startButton"><span>BEGIN RUN</span><b>↗</b></button>
      <div class="instructions"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> STEER</span><span><kbd>←</kbd><kbd>→</kbd> BANK</span><span>COLLECT <i></i> CHARGE</span></div>
    </section>
    <section class="end-panel" id="endPanel" hidden><div class="eyebrow" id="endEyebrow">TRANSMISSION RECEIVED</div><h2 id="endTitle">RELAY FIELD<br><em>STABILIZED</em></h2><p id="endCopy"></p><div class="run-score"><span>SIGNAL SCORE</span><strong id="scoreText">00000</strong></div><button class="launch-button" id="restartButton"><span>RUN AGAIN</span><b>↻</b></button></section>
    <section class="pause-panel" id="pausePanel" hidden><span>PAUSED</span><small>FIELD LINK ON HOLD</small></section>
    <div class="danger" id="danger">IMPACT // HULL DRAIN</div>
    <div class="touch-controls" id="touchControls" aria-label="Touch steering controls"><button id="touchLeft" aria-label="Steer left">◀</button><button id="touchRight" aria-label="Steer right">▶</button></div>
    <div class="corner-data"><span>ALTITUDE 18,400M</span><span id="speedText">CRUISE 0.0</span></div>
  </main>`;

const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(innerWidth, innerHeight); renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.25; app.prepend(renderer.domElement);
const scene = new THREE.Scene(); scene.background = new THREE.Color('#08111f'); scene.fog = new THREE.FogExp2('#08111f', 0.012);
const camera = new THREE.PerspectiveCamera(62, innerWidth / innerHeight, 0.1, 500); camera.position.set(0, 5.1, 13.8);
scene.add(new THREE.HemisphereLight('#8cd7ff', '#11101e', 1.7)); const moon = new THREE.DirectionalLight('#d9ecff', 3.2); moon.position.set(-15, 23, 7); scene.add(moon);
const hotLight = new THREE.PointLight('#4cf3e8', 20, 24, 2); scene.add(hotLight); const redLight = new THREE.PointLight('#ff405e', 13, 18, 2); scene.add(redLight);
const world = new THREE.Group(); scene.add(world); const effects = new THREE.Group(); scene.add(effects); const craft = new THREE.Group(); scene.add(craft);
function mat(color: string, emissive = '#000000', intensity = 0) { return new THREE.MeshStandardMaterial({ color, roughness: .38, metalness: .78, emissive, emissiveIntensity: intensity }); }
const cyan = mat('#83f8ee', '#22e6e0', 2.2), glowBlue = mat('#55afff', '#338fff', 2), dark = mat('#101a2a'), hull = mat('#536779'), hot = mat('#ff6379', '#ff1738', 2.5), gold = mat('#ffd26e', '#ff9f22', 2.7);
function addMesh(group: THREE.Object3D, geometry: THREE.BufferGeometry, material: THREE.Material, x = 0, y = 0, z = 0) { const mesh = new THREE.Mesh(geometry, material); mesh.position.set(x, y, z); group.add(mesh); return mesh; }
const shipBody = addMesh(craft, new THREE.ConeGeometry(.68, 2.65, 4), hull); shipBody.rotation.x = Math.PI / 2; shipBody.rotation.z = Math.PI / 4;
addMesh(craft, new THREE.BoxGeometry(2.15, .12, .62), dark, 0, -.04, .2).rotation.z = -.04; addMesh(craft, new THREE.BoxGeometry(.62, .22, 1.52), dark, 0, .18, -.15).rotation.x = .18; addMesh(craft, new THREE.BoxGeometry(.15, .07, .74), cyan, 0, .2, -.55);
const cockpit = addMesh(craft, new THREE.SphereGeometry(.38, 16, 10), glowBlue, 0, .35, -.14); cockpit.scale.set(.85, .48, 1.35); const engine = addMesh(craft, new THREE.ConeGeometry(.34, 1.4, 12), cyan, 0, 0, .96); engine.rotation.x = -Math.PI / 2; const engineLight = new THREE.PointLight('#38f8ef', 8, 12, 2); engineLight.position.set(0, 0, 1.2); craft.add(engineLight);

const player = new THREE.Vector3(0, 3.2, 6); craft.position.copy(player);
const state = { phase: 'ready' as Phase, score: 0, charge: 100, relays: 0, restartCount: 0, velocityX: 0, velocityY: 0, cameraShake: 0, impactTimer: 0, elapsed: 0 };
const keys = new Set<string>(); let touchSteer = 0; let pointerStart: number | null = null;
let relays: Relay[] = [], pickups: Pickup[] = [], hazards: Hazard[] = [], extraction: THREE.Group | null = null; let clouds: THREE.Sprite[] = [], speedLines: THREE.LineSegments<THREE.BufferGeometry, THREE.LineBasicMaterial> | null = null;
function setPhase(phase: Phase) { state.phase = phase; updateInspect(); }
function updateInspect() { window.__AETHERPLAY__ = { phase: state.phase, score: Math.round(state.score), player: { x: Number(player.x.toFixed(3)), y: Number(player.y.toFixed(3)), z: Number(player.z.toFixed(3)) }, relaysRestored: state.relays, charge: Number(state.charge.toFixed(2)), seed: SEED, restartCount: state.restartCount }; }
declare global { interface Window { __AETHERPLAY__: Record<string, unknown> } }
function clearWorld() { while (world.children.length) world.remove(world.children[0]); relays = []; pickups = []; hazards = []; extraction = null; }
function makeRing(radius: number, tube: number, material: THREE.Material) { return new THREE.Mesh(new THREE.TorusGeometry(radius, tube, 10, 36), material); }
function makeRelay(position: THREE.Vector3, number: number): Relay { const g = new THREE.Group(); g.position.copy(position); world.add(g); const ringA = makeRing(3.0, .15, dark), ringB = makeRing(2.52, .08, hot), core = new THREE.Mesh(new THREE.OctahedronGeometry(.4, 0), hot); ringA.rotation.y = Math.PI / 2; ringB.rotation.y = Math.PI / 2; ringB.rotation.z = .24; g.add(ringA, ringB, core); for (let a = 0; a < 6; a++) { const pylon = addMesh(g, new THREE.BoxGeometry(.16, .16, .8), dark); const t = a / 6 * Math.PI * 2; pylon.position.set(Math.cos(t) * 3.0, Math.sin(t) * 3.0, 0); pylon.rotation.z = t; } const label = addMesh(g, new THREE.TorusGeometry(.22, .04, 5, 12), hot, 0, 0, .1); label.rotation.y = Math.PI / 2; g.userData = { ringA, ringB, core, label }; return { mesh: g, position, restored: false, number }; }
function makePickup(position: THREE.Vector3): Pickup { const g = new THREE.Group(); g.position.copy(position); world.add(g); g.add(new THREE.Mesh(new THREE.OctahedronGeometry(.38, 0), gold)); const halo = makeRing(.62, .035, gold); halo.rotation.x = Math.PI / 2; g.add(halo); g.add(new THREE.PointLight('#ffbf47', 3, 7, 2)); return { mesh: g, position, collected: false, spin: random() * 6.2 }; }
function makeHazard(base: THREE.Vector3, radius = 1.05): Hazard { const g = new THREE.Group(); g.position.copy(base); world.add(g); const shards = new THREE.Group(); g.add(shards); for (let i = 0; i < 5; i++) { const shard = new THREE.Mesh(new THREE.IcosahedronGeometry(.35 + random() * .35, 0), dark); shard.position.set((random()-.5)*1.2, (random()-.5)*1.2, (random()-.5)*.8); shard.rotation.set(random()*3, random()*3, random()*3); shards.add(shard); } const warning = makeRing(radius * .82, .045, hot); warning.rotation.x = Math.PI / 2; g.add(warning); g.add(new THREE.PointLight('#ff3155', 4.5, 9, 2)); return { mesh: g, base, radius, phase: random() * 6.28, sway: .6 + random() * 1.1, hit: false }; }
function makeExtraction(position: THREE.Vector3) { const g = new THREE.Group(); g.position.copy(position); world.add(g); const outer = makeRing(3.8, .22, cyan), inner = makeRing(3.05, .06, glowBlue); outer.rotation.y = Math.PI/2; inner.rotation.y = Math.PI/2; g.add(outer, inner); for (let i=0;i<8;i++) { const dot = new THREE.Mesh(new THREE.SphereGeometry(.13, 8, 8), cyan); const a=i/8*Math.PI*2; dot.position.set(Math.cos(a)*3.43, Math.sin(a)*3.43, 0); g.add(dot); } g.add(new THREE.PointLight('#56f8ee', 12, 25, 2)); extraction = g; }
function makeCourse() { clearWorld(); seed = SEED; const railMat = new THREE.LineBasicMaterial({ color: '#345877', transparent: true, opacity: .42 }); for (const x of [-7.5, 7.5]) { const geo = new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(x, .1, 15), new THREE.Vector3(x, .1, -178)]); world.add(new THREE.Line(geo, railMat)); } for (let z = 8; z > -174; z -= 12) { const left = addMesh(world, new THREE.BoxGeometry(1.3 + random()*1.5, .12, 1.8+random()*2), dark, -8.5-random()*2, -1.0-random()*1.5, z); const right = left.clone(); right.position.x = 8.5 + random()*2; world.add(right); if (random() > .4) { const lamp = new THREE.PointLight('#3db8d5', 2, 5, 2); lamp.position.set((random()>.5?-1:1)*7.5, .4, z); world.add(lamp); } } relays.push(makeRelay(new THREE.Vector3(-2.7, 3.0, -42), 1)); relays.push(makeRelay(new THREE.Vector3(2.9, 3.5, -91), 2)); relays.push(makeRelay(new THREE.Vector3(0, 2.7, -139), 3)); makeExtraction(new THREE.Vector3(0, 3.1, -169)); [[0,3,-15],[-3.1,3,-28],[-2.7,4,-50],[1.7,2.6,-62],[3.1,3.6,-77],[2.9,4,-100],[-2.8,3,-112],[0,2.7,-129],[0,3,-149],[-3,3,-156]].forEach(p => pickups.push(makePickup(new THREE.Vector3(...p)))); [[2.8,3,-25],[-.1,3.1,-35],[-5.2,3,-53],[.2,3,-69],[-2.4,3,-80],[5,3.2,-94],[.2,2.9,-108],[3.3,3,-119],[-3.5,3,-132],[3.8,3,-146],[-3.4,3,-158]].forEach((p,i) => hazards.push(makeHazard(new THREE.Vector3(...p), i%3===0?1.25:.95))); }
function makeAtmosphere() { const starGeo = new THREE.BufferGeometry(), positions: number[] = [], colors: number[] = []; for(let i=0;i<700;i++) { positions.push((random()-.5)*85, random()*32-8, -random()*210+15); const c = new THREE.Color(i%5===0?'#78dfff':'#ffffff'); colors.push(c.r,c.g,c.b); } starGeo.setAttribute('position', new THREE.Float32BufferAttribute(positions,3)); starGeo.setAttribute('color', new THREE.Float32BufferAttribute(colors,3)); effects.add(new THREE.Points(starGeo, new THREE.PointsMaterial({ size:.11, vertexColors:true, transparent:true, opacity:.7, sizeAttenuation:true }))); const streakGeo = new THREE.BufferGeometry(), linePositions: number[] = []; for(let i=0;i<125;i++){ const x=(random()-.5)*27, y=(random()-.15)*16, z=-random()*100+12; linePositions.push(x,y,z,x,y-.35,z+3); } streakGeo.setAttribute('position',new THREE.Float32BufferAttribute(linePositions,3)); speedLines = new THREE.LineSegments(streakGeo,new THREE.LineBasicMaterial({color:'#6cbbdd',transparent:true,opacity:.23})); effects.add(speedLines); const canvas=document.createElement('canvas'); canvas.width=128; canvas.height=128; const ctx=canvas.getContext('2d')!; const grad=ctx.createRadialGradient(64,64,5,64,64,64); grad.addColorStop(0,'rgba(130,174,202,.62)');grad.addColorStop(.45,'rgba(80,120,155,.24)');grad.addColorStop(1,'rgba(7,15,29,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,128,128); const texture = new THREE.CanvasTexture(canvas); const material = new THREE.SpriteMaterial({map:texture,transparent:true,depthWrite:false,opacity:.78,color:'#8fb6cc'}); for(let i=0;i<48;i++){ const cloud=new THREE.Sprite(material); cloud.position.set((random()-.5)*65,-5-random()*7,-random()*220+15); const s=10+random()*19;cloud.scale.set(s,s*.34,1);effects.add(cloud);clouds.push(cloud); } }
makeAtmosphere(); makeCourse(); updateInspect();
const chargeFill = document.querySelector<HTMLElement>('#chargeFill')!, chargeText = document.querySelector<HTMLElement>('#chargeText')!, relayText = document.querySelector<HTMLElement>('#relayText')!, objectiveText = document.querySelector<HTMLElement>('#objectiveText')!, objective = document.querySelector<HTMLElement>('#objective')!, danger = document.querySelector<HTMLElement>('#danger')!, speedText = document.querySelector<HTMLElement>('#speedText')!; const startPanel=document.querySelector<HTMLElement>('#startPanel')!, endPanel=document.querySelector<HTMLElement>('#endPanel')!, pausePanel=document.querySelector<HTMLElement>('#pausePanel')!;
function updateHud() { const c=clamp(state.charge,0,100); chargeFill.style.width=`${c}%`; chargeText.textContent=`${Math.ceil(c)}%`; relayText.textContent=`${state.relays} / 3`; chargeFill.classList.toggle('low',c<28); objectiveText.textContent = state.relays<3 ? `RESTORE RELAY ${state.relays+1} // FOLLOW THE SIGNAL` : 'EXTRACTION RING ONLINE // CROSS THE APERTURE'; objective.classList.toggle('complete',state.relays===3); speedText.textContent=`DRIFT ${Math.round(62 + Math.abs(state.velocityX)*16)}.0`; }
function showEnd(won:boolean) { endPanel.hidden=false; document.querySelector('#endEyebrow')!.textContent=won?'TRANSMISSION RECEIVED':'COURIER LOST'; document.querySelector('#endTitle')!.innerHTML=won?'RELAY FIELD<br><em>STABILIZED</em>':'SIGNAL<br><em>FADING</em>'; document.querySelector('#endCopy')!.textContent=won?'The extraction lattice has your signature. Clean horizon ahead.':'The storm took the last of your charge. Re-enter the field and make the line hold.'; document.querySelector('#scoreText')!.textContent=String(Math.round(state.score)).padStart(5,'0'); }
function begin() { Object.assign(state,{score:0,charge:100,relays:0,velocityX:0,velocityY:0,elapsed:0,impactTimer:0}); player.set(0,3.2,6);craft.position.copy(player); makeCourse(); startPanel.hidden=true;endPanel.hidden=true; setPhase('playing');updateHud(); }
function finish(won:boolean) { setPhase(won?'won':'lost');showEnd(won); } function restart(){ state.restartCount++; begin(); }
document.querySelector('#startButton')!.addEventListener('click',begin); document.querySelector('#restartButton')!.addEventListener('click',restart);
addEventListener('keydown',(e)=>{ keys.add(e.key.toLowerCase()); if((e.key===' '||e.key==='Enter') && state.phase==='ready') begin(); if(e.key.toLowerCase()==='r'&&(state.phase==='lost'||state.phase==='won')) restart(); }); addEventListener('keyup',(e)=>keys.delete(e.key.toLowerCase()));
function bindTouch(id:string, value:number){ const el=document.querySelector<HTMLElement>(id)!; const set=(on:boolean)=>{touchSteer=on?value:touchSteer===value?0:touchSteer}; el.addEventListener('pointerdown',e=>{e.preventDefault();set(true);}); el.addEventListener('pointerup',()=>set(false));el.addEventListener('pointercancel',()=>set(false));el.addEventListener('pointerleave',()=>set(false)); } bindTouch('#touchLeft',-1);bindTouch('#touchRight',1); renderer.domElement.addEventListener('pointerdown',e=>{ if(state.phase==='playing') pointerStart=e.clientX; }); renderer.domElement.addEventListener('pointermove',e=>{ if(pointerStart!==null&&state.phase==='playing'){ touchSteer=clamp((e.clientX-pointerStart)/70,-1,1); }}); addEventListener('pointerup',()=>{pointerStart=null; if(!('ontouchstart' in window)) touchSteer=0;});
document.addEventListener('visibilitychange',()=>{ if(document.hidden&&state.phase==='playing'){setPhase('paused');pausePanel.hidden=false;} else if(!document.hidden&&state.phase==='paused'){setPhase('playing');pausePanel.hidden=true;} }); addEventListener('focus',()=>{if(state.phase==='paused'){setPhase('playing');pausePanel.hidden=true;}});
function restoreRelay(relay:Relay) { relay.restored=true;state.relays++;state.score+=900; const d=relay.mesh.userData as Record<string,THREE.Mesh>; (d.ringB.material as THREE.MeshStandardMaterial).emissive.set('#30ffe9');(d.ringB.material as THREE.MeshStandardMaterial).color.set('#b8fff7');(d.core.material as THREE.MeshStandardMaterial).emissive.set('#42ffe9'); hotLight.position.copy(relay.position); objective.classList.add('flash');setTimeout(()=>objective.classList.remove('flash'),500); }
function hit(h:Hazard) { if(h.hit||state.impactTimer>0)return;h.hit=true;state.charge-=22;state.score=Math.max(0,state.score-75);state.impactTimer=.55;state.cameraShake=.5;danger.classList.add('show');setTimeout(()=>danger.classList.remove('show'),500); setTimeout(()=>h.hit=false,1100); }
const clock = new THREE.Clock(); function animate() { requestAnimationFrame(animate); const dt=Math.min(clock.getDelta(),.05); state.elapsed+=dt; if(state.phase==='playing') { const control=(keys.has('a')||keys.has('arrowleft')?-1:0)+(keys.has('d')||keys.has('arrowright')?1:0)+touchSteer; const vertical=(keys.has('w')||keys.has('arrowup')?1:0)+(keys.has('s')||keys.has('arrowdown')?-1:0); state.velocityX=THREE.MathUtils.damp(state.velocityX,clamp(control,-1,1)*7,5,dt); state.velocityY=THREE.MathUtils.damp(state.velocityY,vertical*4,5,dt); player.x=clamp(player.x+state.velocityX*dt,-7,7);player.y=clamp(player.y+state.velocityY*dt,1.1,6.4);player.z-=11.8*dt; state.charge-=dt*1.34;state.score+=dt*10;state.impactTimer=Math.max(0,state.impactTimer-dt); for(const p of pickups){ if(!p.collected){p.mesh.rotation.y+=dt*2.7;p.mesh.position.y=p.position.y+Math.sin(state.elapsed*2+p.spin)*.24;if(player.distanceTo(p.mesh.position)<1.15){p.collected=true;p.mesh.visible=false;state.charge=clamp(state.charge+20,0,100);state.score+=160;}}} for(const h of hazards){h.mesh.position.x=h.base.x+Math.sin(state.elapsed*h.sway+h.phase)*1.15;h.mesh.position.y=h.base.y+Math.cos(state.elapsed*1.6+h.phase)*.38;h.mesh.rotation.y+=dt*.8;if(player.distanceTo(h.mesh.position)<h.radius+.62)hit(h);} const active=relays[state.relays];if(active&&!active.restored&&player.distanceTo(active.position)<3.0)restoreRelay(active); if(extraction){ extraction.rotation.z+=dt*.35; extraction.children.forEach((o,i)=>{if(i>1)o.rotation.y+=dt*3}); if(state.relays===3&&player.distanceTo(extraction.position)<3.1){state.score+=1500;finish(true);} } if(state.charge<=0)finish(false); } craft.position.lerp(player,.45); craft.rotation.z=THREE.MathUtils.damp(craft.rotation.z,-state.velocityX*.09,7,dt);craft.rotation.x=THREE.MathUtils.damp(craft.rotation.x,state.velocityY*.055,7,dt); craft.rotation.y=Math.sin(state.elapsed*2)*.025; engine.scale.z=1+Math.sin(state.elapsed*22)*.16; const desiredCam=new THREE.Vector3(player.x*.27,player.y+2.15,player.z+8.0); const shake=state.cameraShake*Math.sin(state.elapsed*75); camera.position.lerp(desiredCam,.075);camera.position.x+=shake;camera.lookAt(player.x*.12,player.y+.2,player.z-8);state.cameraShake=Math.max(0,state.cameraShake-dt*1.9); hotLight.position.lerp(player,.08);hotLight.position.z+=2;redLight.position.set(player.x*-.4,player.y+2,player.z-8); if(speedLines){speedLines.position.z=((player.z%18)+18)%18-12;speedLines.material.opacity=state.phase==='playing'?.2+Math.abs(state.velocityX)*.01:.12;} clouds.forEach(c=>{if(c.position.z>player.z+18)c.position.z-=210;}); updateHud();updateInspect();renderer.render(scene,camera); }
animate(); addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);});
