import * as THREE from 'three';
import './style.css';

const root = document.querySelector<HTMLDivElement>('#app');
if (!root) throw new Error('Missing #app root');
root.innerHTML = `
<div id="game"></div><div class="grain"></div><div class="vignette"></div>
<section id="briefing" class="screen active"><div class="brand"><span>TACTICAL AIR COMMAND</span><b>CANYON<br>STRIKE</b><i>OPERATION SUNSPEAR // 07:42</i></div><div class="brief-card"><p class="eyebrow">MISSION 01 · KESTREL FLIGHT</p><h1>Break the canyon defense.</h1><p>Fly the Ember Pass. Destroy three radar sites and intercept the hostile flight, then reach extraction.</p><div class="controls-grid"><span><kbd>W S</kbd><small>PITCH</small></span><span><kbd>A D</kbd><small>ROLL</small></span><span><kbd>Q E</kbd><small>YAW</small></span><span><kbd>SPACE</kbd><small>MISSILE</small></span><span><kbd>SHIFT</kbd><small>AFTERBURNER</small></span><span><kbd>C</kbd><small>CANNON</small></span></div><button id="launch">LAUNCH MISSION <em>↗</em></button><p class="mobile-note">Touch controls activate automatically on mobile</p></div></section>
<div id="hud" class="hidden"><header><div class="callsign"><small>CALLSIGN</small><b>KESTREL 1</b></div><div id="objective" class="objective"><small>PRIMARY OBJECTIVE</small><b>ENTER THE CANYON</b></div><div class="score"><small>SCORE</small><b id="score">000000</b></div></header><div class="left-stack"><div class="readout"><small>SPD</small><b id="speed">480</b><i>KTS</i></div><div class="bar"><span id="throttleBar"></span></div><div class="readout alt"><small>ALT</small><b id="altitude">320</b><i>M</i></div></div><div class="right-stack"><div class="weapon"><small>WEAPON</small><b>FOX-4</b><span id="ammo">08</span><i>MISSILES</i></div><div class="health-label"><small>AIRFRAME</small><b id="healthText">100%</b></div><div class="health"><span id="healthBar"></span></div></div><div id="reticle"><b>+</b></div><div id="lock" class="lock"><b>LOCK</b><i id="distance">-- KM</i></div><div class="radar"><div class="sweep"></div><i class="player-dot"></i><div id="blips"></div><small>RANGE 3.0</small></div><div id="alert"></div><div id="message"></div><div class="bottom-help"><span>WASD</span> FLIGHT &nbsp; <span>SPACE</span> MISSILE &nbsp; <span>C</span> CANNON</div></div>
<div id="touch" class="hidden"><div id="stick"><i></i></div><button id="boostBtn">BOOST</button><button id="fireBtn">FIRE<br><small>MISSILE</small></button><button id="gunBtn">GUN</button></div>
<section id="end" class="screen"><div class="end-card"><p class="eyebrow" id="endLabel">MISSION COMPLETE</p><h2 id="endTitle">CANYON<br>SECURED</h2><div class="debrief"><span><small>FINAL SCORE</small><b id="finalScore">000000</b></span><span><small>TARGETS</small><b id="finalTargets">0 / 6</b></span><span><small>MISSION TIME</small><b id="finalTime">00:00</b></span></div><button id="restart">FLY AGAIN <em>↻</em></button></div></section>`;
const el = <T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;el('game').appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x91bdc8);scene.fog=new THREE.FogExp2(0x73979c,.00019);const camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.1,12000);const clock=new THREE.Clock();
scene.add(new THREE.HemisphereLight(0xc8eff4,0x563728,2.3));const sun=new THREE.DirectionalLight(0xffdfae,3.5);sun.position.set(-800,1400,-500);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.far=3500;sun.shadow.camera.left=-900;sun.shadow.camera.right=900;sun.shadow.camera.top=900;sun.shadow.camera.bottom=-900;scene.add(sun);
const world=new THREE.Group();scene.add(world);
const MAT={rock:new THREE.MeshStandardMaterial({color:0x684638,roughness:.95}),rock2:new THREE.MeshStandardMaterial({color:0x805c45,roughness:1}),sand:new THREE.MeshStandardMaterial({color:0xb98758,roughness:1}),metal:new THREE.MeshStandardMaterial({color:0x293941,metalness:.72,roughness:.3}),red:new THREE.MeshStandardMaterial({color:0xe3402e,emissive:0x5f0802,emissiveIntensity:.8}),glow:new THREE.MeshBasicMaterial({color:0x63d9ff}),dark:new THREE.MeshStandardMaterial({color:0x10191d,metalness:.6,roughness:.25}),white:new THREE.MeshStandardMaterial({color:0xd7d8cc,metalness:.4,roughness:.35})};
function mesh(g:THREE.BufferGeometry,m:THREE.Material,p:number[]=[]){const x=new THREE.Mesh(g,m);x.position.set(p[0]||0,p[1]||0,p[2]||0);x.castShadow=x.receiveShadow=true;return x}
const floor=mesh(new THREE.PlaneGeometry(4000,12500,20,80),MAT.sand,[0,-25,-4500]);floor.rotation.x=-Math.PI/2;world.add(floor);
for(const side of [-1,1])for(let i=0;i<33;i++){const z=500-i*330,inner=420+Math.sin(i*.72)*100,x=side*(inner+220+Math.random()*170),h=380+Math.random()*500;const m=mesh(new THREE.ConeGeometry(300+Math.random()*260,h,7,2),i%3?MAT.rock:MAT.rock2,[x,h/2-15,z]);m.rotation.y=Math.random();m.scale.z=1.3+Math.random();world.add(m);const r=mesh(new THREE.DodecahedronGeometry(240+Math.random()*170),MAT.rock,[side*(inner+480),90+Math.random()*170,z-130]);r.scale.set(1.5,1.5+Math.random(),1.8);world.add(r)}
for(let i=0;i<16;i++){const m=mesh(new THREE.ConeGeometry(600+Math.random()*500,900+Math.random()*900,7),MAT.rock2,[(i%2?1:-1)*(1200+Math.random()*1500),300,-i*700]);m.scale.z=1.5;world.add(m)}
function makeJet(player=false){const g=new THREE.Group(),body=mesh(new THREE.CylinderGeometry(.48,.82,7,8),player?MAT.white:MAT.dark);body.rotation.x=Math.PI/2;g.add(body);const nose=mesh(new THREE.ConeGeometry(.48,2.4,8),player?MAT.white:MAT.dark,[0,0,-4.6]);nose.rotation.x=-Math.PI/2;g.add(nose);const s=new THREE.Shape();s.moveTo(0,-1);s.lineTo(5,2);s.lineTo(4,3);s.lineTo(0,2);s.lineTo(-4,3);s.lineTo(-5,2);s.closePath();const wing=mesh(new THREE.ShapeGeometry(s),MAT.metal);wing.rotation.x=-Math.PI/2;wing.position.z=-.4;g.add(wing);for(const n of [-1,1]){const tail=mesh(new THREE.BoxGeometry(.16,1.8,2.3),player?MAT.red:MAT.dark,[n*.9,.8,2]);tail.rotation.z=n*.25;g.add(tail);const flame=mesh(new THREE.ConeGeometry(.28,2,8),new THREE.MeshBasicMaterial({color:player?0x63d9ff:0xff6a25,transparent:true,opacity:.75}),[n*.45,0,4.4]);flame.rotation.x=Math.PI/2;g.add(flame)}g.scale.setScalar(player?1.25:1.05);return g}
const player=makeJet(true);scene.add(player);
type Target={mesh:THREE.Group,hp:number,max:number,kind:'radar'|'jet',active:boolean,phase:number};const targets:Target[]=[];
function makeRadar(x:number,z:number){const g=new THREE.Group();g.position.set(x,5,z);g.add(mesh(new THREE.CylinderGeometry(8,11,6,8),MAT.dark));g.add(mesh(new THREE.CylinderGeometry(1,1,13,8),MAT.metal,[0,8,0]));const dish=mesh(new THREE.SphereGeometry(9,16,8,0,Math.PI*2,0,Math.PI/2),MAT.white,[0,16,0]);dish.scale.z=.22;dish.rotation.x=Math.PI/2;g.add(dish);const ring=mesh(new THREE.TorusGeometry(11,.5,6,24),MAT.red,[0,1,0]);ring.rotation.x=Math.PI/2;g.add(ring);world.add(g);targets.push({mesh:g,hp:3,max:3,kind:'radar',active:true,phase:Math.random()*6})}
makeRadar(-170,-1300);makeRadar(210,-2850);makeRadar(-120,-4450);for(let i=0;i<3;i++){const j=makeJet();j.position.set((i-1)*220,250+i*50,-3700-i*470);world.add(j);targets.push({mesh:j,hp:2,max:2,kind:'jet',active:true,phase:i*2.1})}
const extract=new THREE.Group();extract.position.set(0,240,-6750);const exMat=new THREE.MeshBasicMaterial({color:0x67ecff,transparent:true,opacity:.35,side:THREE.DoubleSide});for(let i=0;i<3;i++){const r=mesh(new THREE.TorusGeometry(95+i*9,1.3,8,64),exMat);r.rotation.y=Math.PI/2;extract.add(r)}extract.visible=false;world.add(extract);
type Particle={m:THREE.Mesh,v:THREE.Vector3,life:number};type Projectile=Particle&{target?:Target,enemy?:boolean};const particles:Particle[]=[];const shots:Projectile[]=[];
function burst(pos:THREE.Vector3,color=0xff7b28,count=24){for(let i=0;i<count;i++){const m=mesh(new THREE.IcosahedronGeometry(Math.random()*2.5+1),new THREE.MeshBasicMaterial({color,transparent:true}));m.position.copy(pos);scene.add(m);particles.push({m,v:new THREE.Vector3((Math.random()-.5)*80,Math.random()*65,(Math.random()-.5)*80),life:.5+Math.random()*.8})}}
let running=false,ended=false,health=100,ammo=8,score=0,kills=0,time=0,speed=165,stage=0,cooldown=0,enemyCooldown=4;
function lockedTarget(){let best:Target|undefined,aBest=999;const f=new THREE.Vector3(0,0,-1).applyQuaternion(player.quaternion);for(const t of targets)if(t.active){const d=t.mesh.position.clone().sub(player.position),a=f.angleTo(d);if(a<.32&&d.length()<1300&&a<aBest){best=t;aBest=a}}return best}
function missile(){if(ammo<=0){flash('NO MISSILES');return}ammo--;const m=mesh(new THREE.CylinderGeometry(.12,.18,2,6),MAT.white);m.position.copy(player.position);scene.add(m);shots.push({m,v:new THREE.Vector3(0,0,-1).applyQuaternion(player.quaternion).multiplyScalar(310),life:7,target:lockedTarget()});flash(lockedTarget()?'FOX FOUR — MISSILE AWAY':'MISSILE AWAY')}
const keys:Record<string,boolean>={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'){e.preventDefault();if(running&&cooldown<=0){missile();cooldown=.55}}});addEventListener('keyup',e=>keys[e.code]=false);
let tx=0,ty=0,pointer=-1;const stick=el('stick');stick.addEventListener('pointerdown',e=>{pointer=e.pointerId;stick.setPointerCapture(pointer)});stick.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;const r=stick.getBoundingClientRect();tx=THREE.MathUtils.clamp((e.clientX-r.left-r.width/2)/(r.width*.38),-1,1);ty=THREE.MathUtils.clamp((e.clientY-r.top-r.height/2)/(r.height*.38),-1,1);(stick.firstElementChild as HTMLElement).style.transform=`translate(${tx*38}px,${ty*38}px)`});stick.addEventListener('pointerup',()=>{tx=ty=0;pointer=-1;(stick.firstElementChild as HTMLElement).style.transform=''});
el('fireBtn').onpointerdown=()=>{if(running&&cooldown<=0){missile();cooldown=.55}};el('boostBtn').onpointerdown=()=>keys.ShiftLeft=true;el('boostBtn').onpointerup=()=>keys.ShiftLeft=false;el('gunBtn').onpointerdown=()=>keys.KeyC=true;el('gunBtn').onpointerup=()=>keys.KeyC=false;
function flash(s:string,w=false){const m=el('message');m.textContent=s;m.className=w?'warning':'show';setTimeout(()=>{if(m.textContent===s)m.className=''},2200)}
function reset(){health=100;ammo=8;score=0;kills=0;time=0;speed=165;stage=0;ended=false;player.position.set(0,250,450);player.quaternion.identity();targets.forEach(t=>{t.active=true;t.hp=t.max;t.mesh.visible=true});extract.visible=false;el('end').classList.remove('active');el('hud').classList.remove('hidden');if(matchMedia('(pointer:coarse)').matches)el('touch').classList.remove('hidden');running=true;clock.getDelta();flash('MISSION START — FOLLOW THE CANYON')}
el('launch').onclick=()=>{el('briefing').classList.remove('active');reset()};el('restart').onclick=reset;
function finish(win:boolean){if(ended)return;ended=true;running=false;el('hud').classList.add('hidden');el('touch').classList.add('hidden');el('endLabel').textContent=win?'MISSION COMPLETE':'MISSION FAILED';el('endTitle').innerHTML=win?'CANYON<br>SECURED':'AIRCRAFT<br>LOST';el('endLabel').className='eyebrow '+(win?'':'fail');el('finalScore').textContent=String(score).padStart(6,'0');el('finalTargets').textContent=`${kills} / 6`;el('finalTime').textContent=`${String(Math.floor(time/60)).padStart(2,'0')}:${String(Math.floor(time%60)).padStart(2,'0')}`;setTimeout(()=>el('end').classList.add('active'),650)}
function hit(t:Target,n:number){t.hp-=n;burst(t.mesh.position,0xffa33b,7);if(t.hp<=0){t.active=false;t.mesh.visible=false;kills++;score+=t.kind==='radar'?1500:2200;burst(t.mesh.position,0xff641f,38);flash(t.kind==='radar'?'GROUND TARGET DESTROYED':'HOSTILE SPLASHED')}}
const v1=new THREE.Vector3(),v2=new THREE.Vector3();
function update(dt:number){if(!running)return;time+=dt;cooldown-=dt;enemyCooldown-=dt;const pitch=((keys.KeyW?-1:0)+(keys.KeyS?1:0)+ty)*1.05,roll=((keys.KeyA?1:0)+(keys.KeyD?-1:0)-tx)*1.4,yaw=(keys.KeyQ?1:0)+(keys.KeyE?-1:0);player.rotateX(pitch*dt);player.rotateZ(roll*dt);player.rotateY(yaw*dt*.65);const eu=new THREE.Euler().setFromQuaternion(player.quaternion,'YXZ');eu.x=THREE.MathUtils.clamp(eu.x,-.72,.72);eu.z=THREE.MathUtils.lerp(eu.z,0,dt*.32);player.quaternion.setFromEuler(eu);const boost=keys.ShiftLeft||keys.ShiftRight;speed=THREE.MathUtils.lerp(speed,boost?260:165,dt*(boost?1.5:.7));v1.set(0,0,-1).applyQuaternion(player.quaternion);player.position.addScaledVector(v1,speed*dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-570,570);player.position.y=THREE.MathUtils.clamp(player.position.y,30,700);if(player.position.y<48){health-=28*dt;el('alert').textContent='⚠ PULL UP'}else el('alert').textContent='';
targets.forEach(t=>{if(!t.active)return;if(t.kind==='radar'){t.mesh.rotation.y+=dt*.65;return}t.mesh.position.x+=Math.sin(time*.6+t.phase)*30*dt;t.mesh.position.y+=Math.sin(time*.8+t.phase)*9*dt;v1.copy(player.position).sub(t.mesh.position).normalize();t.mesh.quaternion.slerp(new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,-1),v1),dt*.3);if(enemyCooldown<0&&t.mesh.position.distanceTo(player.position)<1000){const m=mesh(new THREE.SphereGeometry(.45,6,6),MAT.red);m.position.copy(t.mesh.position);scene.add(m);shots.push({m,v:v1.clone().multiplyScalar(190),life:5,enemy:true});enemyCooldown=1.8+Math.random()*1.5;flash('MISSILE WARNING',true)}});
if(keys.KeyC&&cooldown<=0){cooldown=.08;const f=new THREE.Vector3(0,0,-1).applyQuaternion(player.quaternion),tr=mesh(new THREE.CylinderGeometry(.045,.045,15,4),MAT.glow);tr.position.copy(player.position).addScaledVector(f,10);tr.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),f);scene.add(tr);particles.push({m:tr,v:f.clone().multiplyScalar(480),life:.16});for(const t of targets)if(t.active){const d=t.mesh.position.clone().sub(player.position);if(d.length()<700&&f.angleTo(d)<.045)hit(t,1)}}
for(const p of shots){if(p.target?.active){v1.copy(p.target.mesh.position).sub(p.m.position).normalize().multiplyScalar(310);p.v.lerp(v1,dt*2.5)}p.m.position.addScaledVector(p.v,dt);p.life-=dt;if(p.enemy&&p.m.position.distanceTo(player.position)<10){health-=24;p.life=0;burst(player.position,0xff3425,12);flash('AIRFRAME HIT',true)}else if(!p.enemy)for(const t of targets)if(t.active&&p.m.position.distanceTo(t.mesh.position)<(t.kind==='radar'?20:12)){hit(t,2);p.life=0;break}if(p.life<=0)scene.remove(p.m)}for(let i=shots.length-1;i>=0;i--)if(shots[i].life<=0)shots.splice(i,1);
for(const p of particles){p.m.position.addScaledVector(p.v,dt);p.v.y-=35*dt;p.life-=dt;(p.m.material as THREE.Material).opacity=Math.max(0,p.life);if(p.life<=0)scene.remove(p.m)}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);
if(health<=0)finish(false);if(kills>=6&&!extract.visible){extract.visible=true;stage=2;flash('ALL TARGETS DOWN — PROCEED TO EXTRACTION')}if(extract.visible){extract.rotation.z+=dt*.3;if(player.position.distanceTo(extract.position)<120)finish(true)}else if(player.position.z<-650)stage=1;hud();const desired=player.position.clone().add(new THREE.Vector3(0,6,24).applyQuaternion(player.quaternion));camera.position.lerp(desired,1-Math.pow(.001,dt));v2.copy(player.position).add(new THREE.Vector3(0,1,-34).applyQuaternion(player.quaternion));camera.lookAt(v2);camera.fov=THREE.MathUtils.lerp(camera.fov,boost?72:64,dt*3);camera.updateProjectionMatrix();sun.position.copy(player.position).add(new THREE.Vector3(-800,1400,-500))}
function hud(){el('speed').textContent=String(Math.round(speed*2.05));el('altitude').textContent=String(Math.round(player.position.y));el('ammo').textContent=String(ammo).padStart(2,'0');el('score').textContent=String(score).padStart(6,'0');el('healthText').textContent=`${Math.max(0,Math.round(health))}%`;el('healthBar').style.width=`${Math.max(0,health)}%`;el('throttleBar').style.width=`${speed/2.6}%`;el('objective').querySelector('b')!.textContent=stage===2?'REACH EXTRACTION':stage===1?`DESTROY HOSTILES  ${kills} / 6`:'ENTER THE CANYON';const t=lockedTarget(),lock=el('lock');if(t){lock.classList.add('active');el('distance').textContent=`${(t.mesh.position.distanceTo(player.position)/1000).toFixed(1)} KM`;const v=t.mesh.position.clone().project(camera);lock.style.left=`${(v.x*.5+.5)*innerWidth}px`;lock.style.top=`${(-v.y*.5+.5)*innerHeight}px`}else lock.classList.remove('active');const blips=el('blips');blips.innerHTML='';targets.filter(t=>t.active).forEach(t=>{const b=document.createElement('i'),d=t.mesh.position.clone().sub(player.position);b.style.left=`${50+THREE.MathUtils.clamp(d.x/25,-42,42)}%`;b.style.top=`${50+THREE.MathUtils.clamp(-d.z/25,-42,42)}%`;blips.appendChild(b)})}
function animate(){requestAnimationFrame(animate);update(Math.min(clock.getDelta(),.04));renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
